### ISSUE TITLE
Nav - Header Container

### ISSUE THREAD

**Issue by well1791** [well1791/trankilino#2]
## Header Container

Seccion header

```feature
Feature: Contenedor de header
  In order to (para tener) una buena experiencia de navegacion,
  As a (como) cliente
  I (yo) quiero que el contenedor de header se mantenga siempre fijo al principio de la pagina

  Scenario: Navegar hasta el final de la pagina
    Given (dado que) estoy en la pagina principal
    When (cuando) haga scroll down hasta el final de la pagina
    Then (entonces) el header debe estar visible

  Scenario: Cambiar de pagina
    Given (dado que) estoy en la pagina principal
    When (cuando) cambie de pagina
    Then (entonces) el header debe mantenerse visible tambien
```

#### Screenshots

![image](https://user-images.githubusercontent.com/6817008/140556575-f799d55d-9455-4812-8e0c-d1c3e743e86e.png)

#### Designs

- https://www.figma.com/file/4KH0jU4Q5Qy06JBKjtfbfA/fifaifofum?node-id=0%3A1

#### Criterio de Aceptación

- [x] El contenedor debe mantenerse estatico, es decir, siempre estara presente aun cuando el usuario haga scroll down
- [x] Ninguno de los iconos (user y brand) o links de navegacion deben programarse todavia
- [x] La linea divisora del header debe estar incluida
- [x] El background del header deberia ser: o sin color o con color blanco;
- [x] El height del header debe cuadrar con el del diseno, actualmente es 52px; incluyendo la linea divisora del header

**Comment by fabi1989** [comment]
revisa xfa, pilas.....

**Comment by well1791** [comment]
@fabi1989 el header no tiene ningun color de background

**diseno**
![image](https://user-images.githubusercontent.com/6817008/140967213-af4bcaaa-e4da-45bb-93d8-b10f4ee92a0f.png)

**pagina**
![image](https://user-images.githubusercontent.com/6817008/140967453-781f278c-b273-4745-b656-f9e842bef816.png)

#### Acceptance criteria
- [ ] El background del header deberia ser: o sin color o con color blanco;

**Comment by well1791** [comment]
@fabi1989 el header tiene un height que no cuadra con el del diseno

#### diseno
![image](https://user-images.githubusercontent.com/6817008/140968128-56bab077-b198-4e4f-9a70-715c21926ef3.png)


#### pagina
![image](https://user-images.githubusercontent.com/6817008/140967929-ff07eca3-1b17-4648-9896-b0951ab2a19d.png)


#### Acceptance criteria
- [ ] El height del header debe cuadrar con el del diseno, actualmente es 52px; incluyendo la linea divisora del header

**Comment by well1791** [comment]
QA Passed
