### ISSUE TITLE
Nav - Page logo

### ISSUE THREAD

**Issue by well1791** [well1791/trankilino#5]
# Page logo

```feature
Feature: Logo del sitio
  In order to tener la marca del sitio,
  As a cliente potencial
  I quiero ver el logo de la sitio para volver al homepage

  Scenario: Estoy en otra pagina del sitio
    Given que estoy en otra pagina del sitio
    When haga click en el logo
    Then debe redireccionarme al homepage
```

#### Screenshots

![image](https://user-images.githubusercontent.com/6817008/140621544-fcddfcdd-4d65-41c8-b3ad-ab05167f9ef1.png)

#### Designs
- https://www.figma.com/file/4KH0jU4Q5Qy06JBKjtfbfA/fifaifofum?node-id=0%3A1

#### Acceptance criteria
- [x] El logo debe estar alineado a la izquierda
- [x] El logo debe estar centrado verticalmente
- [x] Al dar click en el logo debe enviarme al homepage

**Comment by fabi1989** [comment]
esto no se cierra?

**Comment by well1791** [comment]
QA Passed
